name: build-test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: npm ci
        run: npm ci

      - name: Lint
        run: npm run lint-check

      - name: npm test
        run: npm test
