name: Update Status Badges
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  update_status_badges:
    runs-on: ubuntu-latest
    name: Update status badges
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check and update badges
        uses: ./
        with:
          path: 'README.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          stale-timeout: '1 week'